### ISSUE TITLE
Investigate WordPress Pipeline Options

### ISSUE THREAD

**Issue by axrs** [CP3402-2017-1/a2-cp3402-2017-team24#5] opened 2017-04-11 22:55 UTC
We need to integrate a deployment pipeline. The pipeline must allow for `Localhost --> Staging --> Production` style deployments.

Things to consider are also Database Procedures.

**Comment by axrs** [comment] 2017-04-12 00:48
Rock an AWS infrastructure:
- @lrobert142 Production
- @Sedgy Staging

**Comment by axrs** [comment] 2017-04-12 00:49
Still to investigate MySQL Versioning
* May need custom bash to clone/restore

**Comment by lrobert142** [comment] 2017-04-26 01:01
Duplicate of #28

**Closed by lrobert142** 2017-04-26 01:01 UTC
